apiVersion: v1
kind: Pod
metadata:
  name: test-ecr-login
spec:
  containers:
    - name: k8s-util
      image: rkhullar/kubernetes-utils:0.1.0
      imagePullPolicy: IfNotPresent
      args:
        - scripts/ecr-login.sh
      env:
        - name: KUBERNETES_TOKEN
          valueFrom:
            secretKeyRef:
              name: '{service_account_secret}'
              key: token
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: API_SERVER
          value: '{api_server}'
        - name: ECR_CREDS
          value: '{ecr_cred_secret_name}'
        - name: ECR_LOGIN
          value: '{ecr_login_secret_name}'
        - name: AWS_DEFAULT_REGION
          value: '{ecr_region}'
